### ISSUE TITLE
OPENSSL Error while running code

### ISSUE THREAD

**Issue by aishwaryagm1999** [jonasbb/dtls-example#1]
Hi I have installed OpenSSL and set all the paths in environment variables on my windows laptop. I get the following error when I run the code using cargo run.

Error: could not find native static library 'ssl', perhaps -L flag is missing
<img width="1175" alt="Screenshot 2022-05-04 at 2 42 02 PM" src="https://user-images.githubusercontent.com/55407808/166661695-4d70db05-8af5-4180-a0d2-00e3027bdea6.png">

The paths I have set:

<img width="515" alt="Screenshot 2022-05-04 at 2 44 04 PM" src="https://user-images.githubusercontent.com/55407808/166661742-10902e8b-9b15-4248-9feb-4200b1ae2892.png">
<img width="544" alt="Screenshot 2022-05-04 at 2 43 54 PM" src="https://user-images.githubusercontent.com/55407808/166661761-d82929ad-d908-4e34-a31d-60694d80a6f8.png">

**Comment by jonasbb** [comment]
If you have trouble setting up openssl you should contact the maintainers of the openssl crate. You can also see if crate features like `vendored` will help.
